apiVersion: v1
kind: Pod
metadata:
  name: "frontend"
spec:
  containers:
    - name: nginx
      image: "nginx:1.9.14"
      lifecycle:
        preStop:
          exec:
            command: ["/usr/sbin/nginx","-s","quit"]
      volumeMounts:
        - name: "nginx-conf"
          mountPath: "/etc/nginx/conf.d"
        - name: "certs"
          mountPath: "/etc/tls"
  volumes:
    - name: "tls-certs"
      secret:
        secretName: "tls-certs"
    - name: "nginx-conf"
      configMap:
        name: "nginx-frontend"
        items:
          - key: "frontend.conf"
            path: "frontend.conf"
        
